### ISSUE TITLE
Guinea Pig: First time using Nuvigator feedback

### ISSUE THREAD

**Issue by brianegan** [nubank/nuvigator#18] opened 2019-12-10 15:12 UTC
Hey all!

I've been asked by Vini to check out the Nuvigator package and try to use it to provide feedback. I've recorded some notes as I attempted to implement Nuvigator for my first time so I could hopefully provide some constructive feedback!

Also note: It might be easier to chat in person about this stuff than go through a long email chain, haha :) Hit me up and happy to find a time to video chat / discuss!

## Method

  - Read documentation in README
  - Clone repo
  - Run sample and play with the app
  - Look at sample code to understand how pieces fit together
  - Try it for myself!

## First impressions

Note: These first impressions don't mean my opinion is right, but I want to give honest feedback as someone who's familiar with the default Navigator and is looking at this for the first time.

  - Code generation for Route params seems nice!
  - Support out of the box for deeplinks -- yay!
  - README says it works like navigator, "but with several custom improvements and features." It would be helpful if those improvements were explicitly stated right after that line! There's some mention of Deeplinks and nested navigation, but you can handle those scenarios with the default Navigator, so it'd be great to maybe even hear the pain points this library aims to solve.
  - Nuvigator is a child of `MaterialApp` which already has a `Navigator` -- are both needed? Should there be a `NuvigatorApp` which is like `WidgetsApp` or `MaterialApp`?
  - Documentation doesn't have a great "Getting Started" section that you can copy/pasta, need to sort of extract code from the Sample and know how builders work in general
  - When something goes wrong, it's a bit hard to tell why. I got lost when I got the following error a few times: "package:flutter/src/widgets/framework.dart': Failed assertion: line 5438 pos 12: 'child == _child': is not true." This did not include a stacktrace back to any code I had written or was generated. I just played with my code until it generated something different that worked, but I didn't feel confident I'd fixed the issue or really know what the issue was. It feels a bit like you have to understand how this package generates code to understand how to write code to make it happy.
  - Just a gut feeling, but it feels like parts of this package kinda work against the framework a bit. Back buttons in AppBars do not work reliably or show the wrong icon, Android back button works differently than Back buttons in App Bars, no use of `Route` objects to control the animation from one screen to another (kind of buried in the `ScreenRoute` class), passing a parent `BuildContext` into a Widget as a constructor property, extending from classes like `ScreenOneScreen` to get data rather than using Widget composition or passing data into the Widget via constructor properties.
  - So many different `Navigators` to work with! `Nuvigator.of(context)`, `nuvigator` passed into `Screen` widgets (these two might be different than one another depending on the context -- have to look into it more), `SampleOneNavigation`, `SampleOneNavivation.of(context).nestedNavigator`, etc. I kinda miss the beauty of a Widget being completely dumb and just saying "Navigator closest to me in the context, do your job!" rather than having to know exactly which Navigator I'm looking for.

---

Again, these were just my initial impressions. Things like "So many navigators" could easily be seen as "well, the person giving this feedback just doesn't understand the use case and the complexity we're trying to deal with" -- which is true! All I'd say: After using this library for 3-4 hours, I'd probably just write this stuff by hand. Until I got really good with this library, I think it'd actually be a bit less confusing for me.

## Sample

  - Clicking "Go to sample one with Flutter navigation" takes you to "Sample One / Screen One." There's a back button in the AppBar that does not work, but the Android "back" button does indeed work. I'm not sure what the intended effect is here, but did make me a bit "worried" about using this library if those two behaviors are different from one another since it was one of the very first things I tried and it felt like a Navigator library should nail that.
  - Same problem happens if you Navigate from Sample Two -> Sample One
  - It might be good to label the screens a bit differently, such as "1A", "1B", "2A", "2B." Kinda easy to get lost in "Sample Two Screen One"  after coming from "Sample One Screen One".

## Code

  - Most packages that have builders are split into two parts: The Annotations and The Builder. Annotations are included in `dependencies`, the builder is included in the `dev_dependencies` section. Example packages from the dart team: `json_annotations` and `json_serializable`, `built_value` and `built_value_generator`, etc. It might be a good idea to consider a similar split for this library?

## Documentation Improvements

  - Provide Getting Started section with `pubspec.yaml` and `my_router.dart` sample file to get started.
  - Provide a couple of Recipes
    - Regular Navigation scenario
    - Nested Navigation scenario
    - Deeplink scenario
  - FAQ about errors like the ones I got above -- even better, more robust checking in the builder for missing bits. `built_value` is really good at this -- if you forget a part, they let you know exactly what you forgot.

**Comment by leoiacovini** [comment] 2019-12-11 13:16
Hey @brianegan thanks for the amazing feedback! It's very detailed and sure it will help a lot to improve some rough edges :) .

I just want to address some points here, that I believe are going to be useful in the future for another users:

> Nuvigator is a child of MaterialApp which already has a Navigator -- are both needed? Should there be a NuvigatorApp which is like WidgetsApp or MaterialApp?

Actually when using the `builder` property in `MaterialApp` (or Cupertino, etc...) it do not render the default Navigator, that's why we choose to use it, instead of creating a NuvigatorApp that would require a lot of code duplication that it already provided by Flutter's default ones (also it's less code to maintain and give users more flexibility IMO)

> Back buttons in AppBars do not work reliably or show the wrong icon, Android back button works differently than Back buttons in App Bars

If this happened in the example App, then it's by purpose - sadly we used the example App to debug problems that occurred with some users and because of they it's pretty messed up right now, @lubritto will be working on new/better samples soon.
If it happened in another scenario, than this is a bug we must fix. Nuvigator should not remove any feature from the default Navigator, and if something is inconsistent we should take a look.

> No use of Route objects to control the animation from one screen to another (kind of buried in the ScreenRoute class)

This is by design, and it's the way we found to have a declarative approach on which transition each screen should use, and do not need until the Route is pushed to decide this. We may want to take a look if we can simplify this abstraction.

> Passing a parent BuildContext into a Widget as a constructor property, extending from classes like ScreenOneScreen to get data rather than using Widget composition or passing data into the Widget via constructor properties.

This is an optional pattern we found useful for getting typed data into what we are calling `ScreenWidgets` (widgets that should handle the navigation logic only). It's possible to not use it entirely and rely on `ScreenOneArgs.of(context)` to get the arguments, of even from the route method in the Router :) . We will add some samples and documentation regarding those, thanks for the input!

> So many different Navigators to work with! Nuvigator.of(context), nuvigator passed into Screen widgets (these two might be different than one another depending on the context -- have to look into it more), SampleOneNavigation, SampleOneNavivation.of(context).nestedNavigator, etc. I kinda miss the beauty of a Widget being completely dumb and just saying "Navigator closest to me in the context, do your job!" rather than having to know exactly which Navigator I'm looking for.

Totally get this one, and we need to do a better job on explaining this. The short answer is: everytime you grab a nuvigator, it's going to be the closest of you in the context. just like expected :) . Nuvigator.of(context) works just like the Navigator.of(context), but it is enabled to help you when you want to go up the context, for example:
If you are in a nested flow, and want to open a route that is present in the parent Nuvigator, if you call it in the nested one, it will not find it, but will then delegate it to the parent Nuvigator. This way we end with the complexity you told about needing to know which is the right Navigator. That's the whole point about Nuvigator.
Also. most of the time you will be interacting with `SampleOneNavivation.of(context)`, and etc... That you can think about as a wrapper around `Nuvigator.of(context)`, but with typed methods for each route.

---

I believe several point can be addressed with better documentation, and I am working in some of they: https://github.com/nubank/nuvigator/pull/19 , please tell me if you think those will help.

Also, like I said we are going to work on having several examples (separated by complexity level like you suggested) that are not going to be broken :sorry:.

The package separation is also a good suggestion and we should look at it.

Thanks again for the feedback, it's more than welcome and sure it will help us build a better framework both for Nubank and for the community! If anything I said is not clear enough (or I missunderstood some of your points), please feel free to reply or ping me directly (Vini may be able to with that)

**Comment by lubritto** [comment] 2019-12-11 15:15
Hey @brianegan, I want to thank you too for the feedback and suggestions. Like @leoiacovini said we will work to improve the examples, docs, separate the builder and also improve the stacktrace giving more information when something goes wrong.

> No use of Route objects to control the animation from one screen to another (kind of buried in the ScreenRoute class)

About this comment, I want to add that you can set the transition animation using the screenType property inside the ScreenRoute. We will add more docs about this! You can make transitions easily like using the default navigation.

It would be very nice if you try again after these improvements. Thank you again!!

**Comment by brianegan** [comment] 2019-12-11 15:19
Sounds good! Was just reading through the new docs :) 

I'll retry my experiment again with the new info and report back.

**Comment by leoiacovini** [comment] 2020-02-04 23:38
@brianegan I will be closing this issue after the changes made in https://github.com/nubank/nuvigator/pull/20 and the updated doc that I am still working working on at https://github.com/nubank/nuvigator/pull/19 . I created a dedicated issue for the package splitting.
I think we were able to address most of the topics are. Feel free to re-open/open another if you think that there are still something that is not quite clear to you!

Thanks again for the very helpful feedback!

**Closed by leoiacovini** 2020-02-04 23:38 UTC

**Comment by acoutts** [comment] 2020-02-07 16:30
Is there any example for how to use a custom ScreenType to implement entry/exit transitions? I had this working with `PageRouteBuilder` with the default navigation but would love an example showing how to apply this to Nuvigator.

**Comment by acoutts** [comment] 2020-02-07 16:54
Aha this works! For anyone else, here's one using a fade transition enter/exit.

```dart
import 'package:flutter/widgets.dart';
import 'package:nuvigator/nuvigator.dart';

class FadeInOutScreenType extends ScreenType {
  const FadeInOutScreenType();

  @override
  Route<T> toRoute<T extends Object>(
      WidgetBuilder builder, RouteSettings settings) {
    return PageRouteBuilder(
        pageBuilder: (BuildContext context, Animation<double> animation,
            Animation<double> secondaryAnimation) {
          return builder(context);
        },
        settings: settings,
        transitionsBuilder: (_, Animation<double> animation,
                Animation<double> second, Widget child) =>
            FadeTransition(
                opacity: Tween<double>(begin: 0.0, end: 1.0).animate(animation),
                child: FadeTransition(
                  opacity: Tween<double>(begin: 1.0, end: 0.0).animate(second),
                  child: child,
                )));
  }
}

/// Screen which fades in and fades out.
const fadeInOutScreenType = FadeInOutScreenType();
```

**Comment by leoiacovini** [comment] 2020-02-07 18:20
Hi @acoutts !
Yes, that's right, we built Nuvigator to be able to re-use the current method of creating new `PageRoutes` and transitions, so you just need to create a custom `ScreenType` with a `toRoute` function that returns the `PageRoute` you want!
If you want to have a better behavior in nested scenarios, I recommend using the `NuvigatorPageRoute` mixin in a custom page Route class.

You can take a look at how it's done with the defaults Material and Cupertino here:
https://github.com/nubank/nuvigator/blob/master/lib/src/screen_types/material_screen_type.dart

It should be pretty similar to any other case.

Sorry for the lack of documentation, we are working on that, but feel free to ask any doubts or create new issues!
